# Generated by Django 4.2.3 on 2023-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=50),
        ),
    ]
