# Generated by Django 4.2.3 on 2023-08-08 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_moviereaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieReaction',
            new_name='PostReaction',
        ),
    ]
