# Generated by Django 4.2.3 on 2023-08-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_moviereaction_postreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
